### ISSUE TITLE
the cobra tool not working to inject texture to .ovl file

### ISSUE THREAD

**Issue by july702** [OpenNaja/cobra-tools#194]
**Describe the bug**
Step 1: I have successfully unpacked an ovl file and changed the colors, I still keep the png format and the old name.
Step 2: I re-inject the .ovl file and save new .ovl. And when I unpack the new ovl to check, the texture is still the same, nothing has changed.  
I found some bugs attached in the screen shot

**To Reproduce**
1.Go to the Cobra Tools Master Folder
2.Click on ovl_tool_gui.py
3.Open the OVL files of any creature.
4. Unpack into a folder.
**5. An Error appears: 'NoneType' object is not iterable' error****
6.Inject the diffuse file.
**7. An Error appears: 'NoneType' object is not iterable' error****
8. Check new ovl: not have new texture.
**Expected behavior**
Fix error
**Screenshots**
If applicable, 
![2022-05-07_15h58_30](https://user-images.githubusercontent.com/24586204/167247302-941dc996-90ae-4831-b76d-c429865260bf.png)
add scre
![2022-05-07_16h01_08](https://user-images.githubusercontent.com/24586204/167247305-e97a6840-864d-440e-bdf6-da902afa4fd1.png)
enshots to help explain your problem.

**Version Info:**
INFO | Running python 3.7.9 (tags/v3.7.9:13c94747c7, Aug 17 2020, 18:58:18) [MSC v.1900 64 bit (AMD64)]
INFO | Running cobra-tools 2.3.8, f8e499c8 - Thu May 5 21:38:16 2022 +0200
Phiên bản máy xay sinh tố: 3.1.0
 **Log Files:**
 - Close the tools and attach the appropriate log file here. [e.g. cobra-tools/ovl_tool_gui.log]
[ovl_tool_gui.log](https://github.com/OpenNaja/cobra-tools/files/8644779/ovl_tool_gui.log)

AND SOME TEXT LOG I FOUND FROM test.bat
[from test.bat.txt](https://github.com/OpenNaja/cobra-tools/files/8644819/from.test.bat.txt)

**Comment by HENDRIX-ZT2** [comment]
Fgm issue is fixed, texture injection should work too.

**Comment by july702** [comment]
Thank you so much.

**Comment by july702** [comment]
**Describe the bug**
Step 1: I have successfully unpacked an ovl file and changed the colors of texture, I still keep the png format and the old name.
Step 2: I re-inject the .ovl file and save new .ovl. And when I unpack the new ovl to check, the texture is still the same, nothing has changed.
I found error: WARNING | Unsupported file type:
**To Reproduce**
Steps to reproduce the behavior:
1.Go to the Cobra Tools Master Folder
2.Click on ovl_tool_gui.py
3.Open the OVL files of any creature.
4. Unpack into a folder.
5. Inject the diffuse file.
7. An Error appears: WARNING | Unsupported file type: tyrannosaurusrex.pbasediffusetexture.png (in my case, i tried inject new texture of Rex JWE)
8. Save and Check new ovl: not have new texture.
Expected behavior
Fix error
Screenshots
![2022-05-08_11h23_40](https://user-images.githubusercontent.com/24586204/167281772-9018b439-6a46-4628-b9fb-6780e5a9cffb.png)

Version Info:
INFO | Running python 3.7.9 (tags/v3.7.9:13c94747c7, Aug 17 2020, 18:58:18) [MSC v.1900 64 bit (AMD64)]
INFO | Running cobra-tools 2.3.8, 046f2fd5 - Sat May 7 22:45:05 2022 +0200
Log Files:
[ovl_tool_gui.log](https://github.com/OpenNaja/cobra-tools/files/8646341/ovl_tool_gui.log)

[Log from cmd when running cobra tool.txt](https://github.com/OpenNaja/cobra-tools/files/8646342/Log.from.cmd.when.running.cobra.tool.txt)

[Log from test.bat.txt](https://github.com/OpenNaja/cobra-tools/files/8646344/Log.from.test.bat.txt)
#194

**Comment by HENDRIX-ZT2** [comment]
You need to inject the Tex file instead of the PNG. The Tex file must be located in the same spot as the PNG so it can then load the required pngs automatically.

**Comment by july702** [comment]
I tried to use the .tex file but still the error occurs. I made a demonstration video. Can you help me see where I am going wrong. I refer to the videos from youtube mostly showing the instructions for using the old versions and I have seen direct injection with png files.
[https://www.youtube.com/watch?v=ksayNdClEXY](url)
